server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: service-1
              uri: lb://service1
              predicates:
                - Path=/service1/**
            - id: service-2
              uri: lb://service2
              predicates:
                - Path=/service2/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

