apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: service1:1.0
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER
              value: "http://eurekaserver:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
