server:
  port: 8082

spring:
  application:
    name: service2

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      instanceId: ${vcap.application.name}:${vcap.application.instance_id}
